# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load_audio = QtWidgets.QPushButton(self.centralwidget)
        self.load_audio.setGeometry(QtCore.QRect(60, 30, 75, 23))
        self.load_audio.setObjectName("load_audio")
        self.gc = QtWidgets.QPushButton(self.centralwidget)
        self.gc.setGeometry(QtCore.QRect(550, 110, 121, 23))
        self.gc.setObjectName("gc")
        self.pitch = QtWidgets.QLabel(self.centralwidget)
        self.pitch.setGeometry(QtCore.QRect(400, 50, 31, 20))
        self.pitch.setObjectName("pitch")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(260, 50, 75, 23))
        self.play.setObjectName("play")
        self.pause = QtWidgets.QPushButton(self.centralwidget)
        self.pause.setGeometry(QtCore.QRect(260, 80, 75, 23))
        self.pause.setObjectName("pause")
        self.export_audio = QtWidgets.QPushButton(self.centralwidget)
        self.export_audio.setGeometry(QtCore.QRect(60, 130, 75, 23))
        self.export_audio.setObjectName("export_audio")
        self.speed = QtWidgets.QLabel(self.centralwidget)
        self.speed.setGeometry(QtCore.QRect(400, 90, 31, 20))
        self.speed.setObjectName("speed")
        self.gc_result = QtWidgets.QTextBrowser(self.centralwidget)
        self.gc_result.setGeometry(QtCore.QRect(550, 30, 191, 71))
        self.gc_result.setObjectName("gc_result")
        self.speed_spin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.speed_spin.setGeometry(QtCore.QRect(440, 90, 62, 22))
        self.speed_spin.setMinimum(0.0)
        self.speed_spin.setSingleStep(0.25)
        self.speed_spin.setProperty("value", 1.0)
        self.speed_spin.setObjectName("speed_spin")
        self.pitch_spin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pitch_spin.setGeometry(QtCore.QRect(440, 50, 62, 22))
        self.pitch_spin.setMinimum(-100.0)
        self.pitch_spin.setProperty("value", 1.0)
        self.pitch_spin.setObjectName("pitch_spin")
        self.export_name = QtWidgets.QLineEdit(self.centralwidget)
        self.export_name.setGeometry(QtCore.QRect(60, 100, 113, 20))
        self.export_name.setObjectName("export_name")
        self.wav = QtWidgets.QLabel(self.centralwidget)
        self.wav.setGeometry(QtCore.QRect(180, 110, 47, 12))
        self.wav.setObjectName("wav")
        self.enterExportNmae = QtWidgets.QLabel(self.centralwidget)
        self.enterExportNmae.setGeometry(QtCore.QRect(60, 80, 121, 16))
        self.enterExportNmae.setObjectName("enterExportNmae")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SimpleMIR"))
        self.load_audio.setText(_translate("MainWindow", "Load Audio"))
        self.gc.setText(_translate("MainWindow", "Genre Classifycation"))
        self.pitch.setText(_translate("MainWindow", "Pitch"))
        self.play.setText(_translate("MainWindow", "Play"))
        self.pause.setText(_translate("MainWindow", "Pause"))
        self.export_audio.setText(_translate("MainWindow", "Export Audio"))
        self.speed.setText(_translate("MainWindow", "Speed"))
        self.wav.setText(_translate("MainWindow", ".wav"))
        self.enterExportNmae.setText(_translate("MainWindow", "Enter expoet name:"))
