# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load_audio = QtWidgets.QPushButton(self.centralwidget)
        self.load_audio.setGeometry(QtCore.QRect(50, 20, 75, 23))
        self.load_audio.setObjectName("load_audio")
        self.gc = QtWidgets.QPushButton(self.centralwidget)
        self.gc.setGeometry(QtCore.QRect(390, 20, 121, 23))
        self.gc.setObjectName("gc")
        self.pitch = QtWidgets.QLabel(self.centralwidget)
        self.pitch.setGeometry(QtCore.QRect(280, 20, 31, 20))
        self.pitch.setObjectName("pitch")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(170, 20, 75, 23))
        self.play.setObjectName("play")
        self.pause = QtWidgets.QPushButton(self.centralwidget)
        self.pause.setGeometry(QtCore.QRect(170, 50, 75, 23))
        self.pause.setObjectName("pause")
        self.export_audio = QtWidgets.QPushButton(self.centralwidget)
        self.export_audio.setGeometry(QtCore.QRect(50, 50, 75, 23))
        self.export_audio.setObjectName("export_audio")
        self.speed = QtWidgets.QLabel(self.centralwidget)
        self.speed.setGeometry(QtCore.QRect(280, 50, 31, 20))
        self.speed.setObjectName("speed")
        self.gc_result = QtWidgets.QTextBrowser(self.centralwidget)
        self.gc_result.setGeometry(QtCore.QRect(390, 50, 261, 51))
        self.gc_result.setObjectName("gc_result")
        self.speed_spin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.speed_spin.setGeometry(QtCore.QRect(320, 50, 62, 22))
        self.speed_spin.setMinimum(0.0)
        self.speed_spin.setSingleStep(0.25)
        self.speed_spin.setProperty("value", 1.0)
        self.speed_spin.setObjectName("speed_spin")
        self.pitch_spin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pitch_spin.setGeometry(QtCore.QRect(320, 20, 62, 22))
        self.pitch_spin.setMinimum(-100.0)
        self.pitch_spin.setProperty("value", 1.0)
        self.pitch_spin.setObjectName("pitch_spin")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SimpleMIR"))
        self.load_audio.setText(_translate("MainWindow", "Load Audio"))
        self.gc.setText(_translate("MainWindow", "Genre Classifycation"))
        self.pitch.setText(_translate("MainWindow", "Pitch"))
        self.play.setText(_translate("MainWindow", "Play"))
        self.pause.setText(_translate("MainWindow", "Pause"))
        self.export_audio.setText(_translate("MainWindow", "Export Audio"))
        self.speed.setText(_translate("MainWindow", "Speed"))
