# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 408)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.load_audio = QtWidgets.QPushButton(self.centralwidget)
        self.load_audio.setGeometry(QtCore.QRect(60, 30, 91, 23))
        self.load_audio.setObjectName("load_audio")
        self.gc = QtWidgets.QPushButton(self.centralwidget)
        self.gc.setGeometry(QtCore.QRect(490, 70, 121, 23))
        self.gc.setObjectName("gc")
        self.pitch = QtWidgets.QLabel(self.centralwidget)
        self.pitch.setGeometry(QtCore.QRect(70, 110, 31, 20))
        self.pitch.setObjectName("pitch")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(180, 30, 75, 23))
        self.play.setObjectName("play")
        self.pause = QtWidgets.QPushButton(self.centralwidget)
        self.pause.setGeometry(QtCore.QRect(280, 30, 75, 23))
        self.pause.setObjectName("pause")
        self.export_audio = QtWidgets.QPushButton(self.centralwidget)
        self.export_audio.setGeometry(QtCore.QRect(60, 270, 91, 23))
        self.export_audio.setObjectName("export_audio")
        self.speed = QtWidgets.QLabel(self.centralwidget)
        self.speed.setGeometry(QtCore.QRect(70, 150, 31, 20))
        self.speed.setObjectName("speed")
        self.gc_result = QtWidgets.QTextBrowser(self.centralwidget)
        self.gc_result.setGeometry(QtCore.QRect(490, 110, 191, 71))
        self.gc_result.setObjectName("gc_result")
        self.speed_spin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.speed_spin.setGeometry(QtCore.QRect(110, 150, 62, 22))
        self.speed_spin.setMinimum(0.0)
        self.speed_spin.setSingleStep(0.25)
        self.speed_spin.setProperty("value", 1.0)
        self.speed_spin.setObjectName("speed_spin")
        self.pitch_spin = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.pitch_spin.setGeometry(QtCore.QRect(110, 110, 62, 22))
        self.pitch_spin.setMinimum(-100.0)
        self.pitch_spin.setProperty("value", 1.0)
        self.pitch_spin.setObjectName("pitch_spin")
        self.export_name = QtWidgets.QLineEdit(self.centralwidget)
        self.export_name.setGeometry(QtCore.QRect(60, 240, 113, 20))
        self.export_name.setObjectName("export_name")
        self.wav = QtWidgets.QLabel(self.centralwidget)
        self.wav.setGeometry(QtCore.QRect(180, 250, 47, 12))
        self.wav.setObjectName("wav")
        self.enterExportNmae = QtWidgets.QLabel(self.centralwidget)
        self.enterExportNmae.setGeometry(QtCore.QRect(60, 220, 121, 16))
        self.enterExportNmae.setObjectName("enterExportNmae")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 80, 101, 16))
        self.label.setObjectName("label")
        self.target_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.target_comboBox.setGeometry(QtCore.QRect(250, 110, 141, 22))
        self.target_comboBox.setObjectName("target_comboBox")
        self.target_comboBox.addItem("")
        self.target_comboBox.addItem("")
        self.target_comboBox.addItem("")
        self.transfer_button = QtWidgets.QPushButton(self.centralwidget)
        self.transfer_button.setGeometry(QtCore.QRect(250, 150, 61, 28))
        self.transfer_button.setObjectName("transfer_button")
        self.recover_button = QtWidgets.QPushButton(self.centralwidget)
        self.recover_button.setGeometry(QtCore.QRect(330, 150, 61, 28))
        self.recover_button.setObjectName("recover_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 727, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SimpleMIR"))
        self.load_audio.setText(_translate("MainWindow", "Load Audio"))
        self.gc.setText(_translate("MainWindow", "Genre Classifycation"))
        self.pitch.setText(_translate("MainWindow", "Pitch"))
        self.play.setText(_translate("MainWindow", "Play"))
        self.pause.setText(_translate("MainWindow", "Pause"))
        self.export_audio.setText(_translate("MainWindow", "Export Audio"))
        self.speed.setText(_translate("MainWindow", "Speed"))
        self.wav.setText(_translate("MainWindow", ".wav"))
        self.enterExportNmae.setText(_translate("MainWindow", "Enter expoet name:"))
        self.label.setText(_translate("MainWindow", "Timbre Transfer"))
        self.target_comboBox.setItemText(0, _translate("MainWindow", "Trumpet"))
        self.target_comboBox.setItemText(1, _translate("MainWindow", "Violin"))
        self.target_comboBox.setItemText(2, _translate("MainWindow", "Acoustic Guitar"))
        self.transfer_button.setText(_translate("MainWindow", "Transfer"))
        self.recover_button.setText(_translate("MainWindow", "Recover"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

